### PR TITLE
feat ( code linting ): Outlaw "comma dangle", make "comma-style": "first"

### PR DESCRIPTION
**Pull request by Emuentes**
Outlaw the "comma dangle" errors because it's an anti-pattern, switch to first instead of last comma.

### CODE REVIEW

**Comment by schmooie** [comment]
One woman's anti-pattern is another woman's best practice

**Comment by dansternfeld** [comment]
"Anti-pattern? Them's fightin' words!"

I think it's fair to call the trailing comma an anti-pattern because the code is immediately removed by the transpiler. Plus, the only purpose it serves is to reduce _line count_ on git diffs, not actual diff amount in characters, not conflicts. It's a developer "convenience" that leads to a bad habit / assumption about the project. (Mostly, it offends me because it's invalid JSON in object creation code. With destructuring & such, I'll have to get over that hump, but this feels like a bridge too far.)

I wouldn't go so far as to say comma-first is the greatest thing ever, but it is more readable and has the benefit of also being valid syntax.

(lol, hey, @schmooie)

**Comment by schmooie** [comment]
But dangling commas don't apply to JSON!

**Comment by broox9** [comment]
honestly comma style 'first' is an anti-pattern for my eyes.  It's SQL-y and I dislike it when reading code.  Code style more about communication with other humans than it is about communicating with machines.

**Comment by dansternfeld** [comment]
@broox9 I think the comma-first style _improves_ the human communication. With comma at the end, it's easier to miss one inside the list -- when a comma-first line is missing the comma, it stands out on the left side, which we read first. (I assume that's why it's commonly done in SQL as well, where syntax is less forgiving.)

Of course, just adding commas at the end everywhere reduces the risk as well, but that's the _real_ anti-pattern we're trying to address.

**Comment by evanpipta** [comment]
I don't know if I would say anti-pattern but dangling comma feels wrong me because it's invalid JSON which makes me have to switch coding style depending on whether I'm working on a js or json file. And usually most of the objects where I'm copying and pasting properties are json which makes it weird to switch between dangling comma and no dangling comma. I prefer the regular "comma at the end", because that's the standard for how json is formatted by things like npm and it keeps object literal syntax somewhat consistent with that.

@dansternfeld Agreed that comma first makes a missing comma stand out better than anything else though which is good! Although if you have a linter running in the background then a missing comma will stand out regardless of which style is used :)

**Comment by schmooie** [comment]
@747823 makes a good point about missing commas standing out, regardless of whether the comma-first rule is implemented.

I'd much rather remove the dangling comma rule than to enact the comma first rule.

**Comment by joshbDev** [comment]
jumping in on this. We had a lot of back and forth when we first decided to implement it (which is also why it's a warning and not an error (though from the look of it that may have changed)), basically we decided to try it because it aligns closely with most style guides out there (see https://github.com/airbnb/javascript#commas--dangling and https://www.npmjs.com/package/javascript-styleguide#trailing-commas). I can't seem to find a large reputable body that is using comma first as an enforcer. At the end of the day though, it is about readable code.

(If you actually want my opinion, I've grown on the idea of the trailing comma. you'll find it with most React tutorials)

**Comment by broox9** [comment]
I've grown on the dangling comma too because i when writing code I can copy lines and not do the annoying "remove the comma at the end of the last one in the set" thing. It's a nice convenience.

... and yes, i know comma first allows this too, i just don't like looking at comma first code.

**Comment by ghost** [comment]
Driving by for 2 cents:

The reasoning of enforcing the **_Last-Comma_** rule is not quite convincing with only 2 benefits (_1) better diff with one less diff line_, & _2) flexibility to add or remove a object property in any order inside the object_), which have been the previous **_Leading Comma_** pattern had already introduced the benefits.

Personally, the originator of the **_Last/Trailing Comma_** pattern should have been debated for the anti-pattern in core JavaScript feature, to demote the discipline of having clean and consistent code, without any convincing benefits.

Such linting rule is a loophole to encourage any engineer to break any core language syntax and adapt to abuse the permissive nature of JavaScript. It's a first step to destroy clean-code discipline.

Someone else will soon figure out another permissive syntax shortcut in JavaScript, to support another trivial, non-significant benefit to the linter, and publish the subjective rule to the open-source community.  At that point, should a project team catch the hype without researching much and adapt the rule, because the count of npm or GitHub download shows popularity?  I hope the opinion can be more conservation on this scenario.

**Comment by ghost** [comment]
Another objective use case I'd give:

What if **_Babel_** for some reason decides to drop the support for trimming last comma, in their updated rules of transpiling?

What would happen to the dependency & assumption of "Babel would trim the **_Last-Comma_** rule by transpiler?

Would the team need to find another transpiler that supports to trim the last comma?

Is the effort to research again and update the linting rules considered overhead?

**Comment by joshbDev** [comment]
@bcVamp Trailing commas became understandable in ES5, so every browser that you support has the ability to handle a trailing comma (see https://blogs.msdn.microsoft.com/ie/2010/06/25/enhanced-scripting-in-ie9-ecmascript-5-support-and-more/ for ie9 support). Babel or no, that shouldn't have an opinion on this.

**Comment by Emuentes** [comment]
Suggested dropping dangling commas

**Comment by Emuentes** [comment]
So @chrisrng, what's the process here? Does this pull request get rejected or merged?

I suggest as an alternative to forcing this... we set:
 `"comma-dangle": [2, "only-multiline"],`
This will suggest but not require that a dangling comma be added.

Further I suggest leaving `"comma-style": [2, "last"],` the way it is.

Can the participants of this ticket agree to those conditions?

@schmooie @dansternfeld @broox9 @747823 @bcVamp @thehindenburg ?

**Comment by chrisrng** [comment]
Hey @Emuentes that sounds good, lets try to find some common ground here and get a rule everyone will accept

**Comment by Emuentes** [comment]
PR updated to be more accommodating.

**Comment by broox9** [comment]
👍

**Comment by Emuentes** [comment]
Alright gang, I see 2 thumbs up & one "sounds good". As there has been no further argument, we are going to merge this in.

**Pull request merged**
